name: 'Check Dependency Changes'
description: 'Check if dependent files have changed since the last commit'

branding:
  icon: 'filter'
  color: 'purple'
      
inputs:
  fileSeparator:
    description: "Split character for output strings."
    required: false
    default: ","
  filePath:
    description: 'Path to the file to check dependencies for'
    required: true
  tsConfigPath:
    description: 'Path to the tsconfig'
    required: false
    default: './tsconfig.json'
outputs:
  dependencyChanged:
    description: 'Boolean indicating if any dependency has changed'

runs:
    using: 'node20'
    main: 'dist/index.js'

